# Домашнее задание 5

Перед выполнением заданий необходимо сохранить копию этого блокнота себе на диск. Или скачать `.ipynb`/`.py` файл для локальной разработки.

За работу можно получить максимум 8 баллов.

## Полным полна коробочка (1 балл)


Создайте список, содержащий: вектор, матрицу и подсписок.
Обратитесь к элементам списка разными способами ($, [[ ]], [ ]).
Измените один элемент в подсписке.

In [1]:
# Создаем список, содержащий вектор, матрицу и подсписок
my_list <- list(
  vector = c(1, 2, 3, 4, 5),
  matrix = matrix(1:9, nrow = 3, ncol = 3),
  sublist = list(a = 10, b = 20, c = 30)
)

# Выводим список
print("Созданный список:")
print(my_list)

# Обращение к элементам списка разными способами
print("\n1. Обращение с помощью $:")
print(my_list$vector)
print(my_list$matrix)
print(my_list$sublist)

print("\n2. Обращение с помощью [[]]:")
print(my_list[[1]])  # Первый элемент (вектор)
print(my_list[[2]])  # Второй элемент (матрица)
print(my_list[[3]])  # Третий элемент (подсписок)

print("\n3. Обращение с помощью [] (получение подсписка):")
print(my_list[1])    # Подсписок с первым элементом
print(my_list[2])    # Подсписок со вторым элементом
print(my_list[3])    # Подсписок с третьим элементом

print("\n4. Обращение к элементам подсписка:")
print(my_list$sublist$a)          # Через $
print(my_list[[3]]$b)            # Через комбинацию
print(my_list$sublist[["c"]])    # Через [[ ]]

# Изменяем один элемент в подсписке
print("\nДо изменения:")
print(my_list$sublist$b)

my_list$sublist$b <- 999

print("\nПосле изменения (b изменен на 999):")
print(my_list$sublist$b)
print("\nВесь список после изменения:")
print(my_list)

[1] "Созданный список:"
$vector
[1] 1 2 3 4 5

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$sublist
$sublist$a
[1] 10

$sublist$b
[1] 20

$sublist$c
[1] 30


[1] "\n1. Обращение с помощью $:"
[1] 1 2 3 4 5
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
$a
[1] 10

$b
[1] 20

$c
[1] 30

[1] "\n2. Обращение с помощью [[]]:"
[1] 1 2 3 4 5
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
$a
[1] 10

$b
[1] 20

$c
[1] 30

[1] "\n3. Обращение с помощью [] (получение подсписка):"
$vector
[1] 1 2 3 4 5

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$sublist
$sublist$a
[1] 10

$sublist$b
[1] 20

$sublist$c
[1] 30


[1] "\n4. Обращение к элементам подсписка:"
[1] 10
[1] 20
[1] 30
[1] "\nДо изменения:"
[1] 20
[1] "\nПосле изменения (b изменен на 999):"
[1] 999
[1] "\nВесь список после изменения:"
$vector
[1] 1 2 3 4 5

$matrix
     [,1] [,2] [,3]
[1

## Матрицы атакуют (1 балл)

Найти решение системы

$$
\begin{equation}
\begin{cases}
\xi_1 & + & 2 \xi_2 & + & 3 \xi_3 & + & 4 \xi_4 & + & 5 \xi_5 & = & 2
\\
2\xi_1 & + & 3 \xi_2 & + & 7 \xi_3 & + & 10 \xi_4 & + & 13 \xi_5 & = & 12
\\
3\xi_1 & + & 5 \xi_2 & + & 11 \xi_3 & + & 16 \xi_4 & + & 21 \xi_5 & = & 17
\\
2\xi_1 & - & 7 \xi_2 & + & 7 \xi_3 & + & 7 \xi_4 & + & 2 \xi_5 & = & 57
\\
\xi_1 & + & 4 \xi_2 & + & 5 \xi_3 & + & 3 \xi_4 & + & 10 \xi_5 & = & 7
\end{cases}
\end{equation}
$$

PS: используйте встроенные в R функции решения систем.

In [2]:
# Решение системы линейных уравнений
# Система:
# ξ1 + 2ξ2 + 3ξ3 + 4ξ4 + 5ξ5 = 2
# 2ξ1 + 3ξ2 + 7ξ3 + 10ξ4 + 13ξ5 = 12
# 3ξ1 + 5ξ2 + 11ξ3 + 16ξ4 + 21ξ5 = 17
# 2ξ1 - 7ξ2 + 7ξ3 + 7ξ4 + 2ξ5 = 57
# ξ1 + 4ξ2 + 5ξ3 + 3ξ4 + 10ξ5 = 7

# Коэффициенты системы (матрица A)
A <- matrix(c(
  1, 2, 3, 4, 5,
  2, 3, 7, 10, 13,
  3, 5, 11, 16, 21,
  2, -7, 7, 7, 2,
  1, 4, 5, 3, 10
), nrow = 5, ncol = 5, byrow = TRUE)

# Правая часть системы (вектор b)
b <- c(2, 12, 17, 57, 7)

print("Матрица коэффициентов A:")
print(A)

print("\nВектор правой части b:")
print(b)

# Решаем систему с помощью solve()
solution <- solve(A, b)

print("\nРешение системы:")
print(solution)

# Проверяем решение
print("\nПроверка (A * x):")
print(A %*% solution)

print("\nДолжно быть равно b:")
print(b)

# Альтернативный способ: через обратную матрицу
print("\nАльтернативное решение через обратную матрицу:")
solution_alt <- solve(A) %*% b
print(solution_alt)

# Выводим решение в читаемом формате
print("\nРешение в читаемом формате:")
cat(sprintf("ξ1 = %.4f\n", solution[1]))
cat(sprintf("ξ2 = %.4f\n", solution[2]))
cat(sprintf("ξ3 = %.4f\n", solution[3]))
cat(sprintf("ξ4 = %.4f\n", solution[4]))
cat(sprintf("ξ5 = %.4f\n", solution[5]))

[1] "Матрица коэффициентов A:"
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    2    3    7   10   13
[3,]    3    5   11   16   21
[4,]    2   -7    7    7    2
[5,]    1    4    5    3   10
[1] "\nВектор правой части b:"
[1]  2 12 17 57  7
[1] "\nРешение системы:"
[1]  3 -5  4 -2  1
[1] "\nПроверка (A * x):"
     [,1]
[1,]    2
[2,]   12
[3,]   17
[4,]   57
[5,]    7
[1] "\nДолжно быть равно b:"
[1]  2 12 17 57  7
[1] "\nАльтернативное решение через обратную матрицу:"
     [,1]
[1,]    3
[2,]   -5
[3,]    4
[4,]   -2
[5,]    1
[1] "\nРешение в читаемом формате:"
ξ1 = 3.0000
ξ2 = -5.0000
ξ3 = 4.0000
ξ4 = -2.0000
ξ5 = 1.0000


## Снова матрицы (1 балл)

Создайте матрицу 5 на 5, заполнив ее произвольными числами.

* выведите элемент из третей строки и четвертого столбца
* замените значения второго столбца на ваш номер ИСУ без первой цифры
* вычислить сумму значений по каждой строке и каюдому столбцу

Рекомендуем для проверки выводить в консоль промежуточные значения матрицы.

In [3]:
# Создаем матрицу 5x5 с произвольными числами
set.seed(42) # Для воспроизводимости
mat <- matrix(sample(1:100, 25, replace = TRUE), nrow = 5, ncol = 5)

print("Исходная матрица 5x5:")
print(mat)

# Выводим элемент из третьей строки и четвертого столбца
element <- mat[3, 4]
cat(sprintf("\nЭлемент в 3-й строке, 4-м столбце: %d\n", element))

# Заменяем значения второго столбца на номер ИСУ без первой цифры
# Предположим, номер ИСУ: 311469 -> без первой цифры: 11469
isu_number <- 11469
mat[, 2] <- isu_number

print("\nМатрица после замены второго столбца:")
print(mat)

# Вычисляем сумму по каждой строке
row_sums <- rowSums(mat)
print("\nСумма по каждой строке:")
print(row_sums)

# Вычисляем сумму по каждому столбцу
col_sums <- colSums(mat)
print("\nСумма по каждому столбцу:")
print(col_sums)

# Выводим итоговую матрицу с суммами
print("\nИтоговая матрица с суммами строк и столбцов:")
print(mat)
cat("\nСуммы строк: "); print(row_sums)
cat("Суммы столбцов: "); print(col_sums)

[1] "Исходная матрица 5x5:"
     [,1] [,2] [,3] [,4] [,5]
[1,]   49   18  100    3   95
[2,]   65   49   89   41    5
[3,]   25   47   37   89   84
[4,]   74   24   20   27   34
[5,]  100   71   26   36   92

Элемент в 3-й строке, 4-м столбце: 89
[1] "\nМатрица после замены второго столбца:"
     [,1]  [,2] [,3] [,4] [,5]
[1,]   49 11469  100    3   95
[2,]   65 11469   89   41    5
[3,]   25 11469   37   89   84
[4,]   74 11469   20   27   34
[5,]  100 11469   26   36   92
[1] "\nСумма по каждой строке:"
[1] 11716 11669 11704 11624 11723
[1] "\nСумма по каждому столбцу:"
[1]   313 57345   272   196   310
[1] "\nИтоговая матрица с суммами строк и столбцов:"
     [,1]  [,2] [,3] [,4] [,5]
[1,]   49 11469  100    3   95
[2,]   65 11469   89   41    5
[3,]   25 11469   37   89   84
[4,]   74 11469   20   27   34
[5,]  100 11469   26   36   92

Суммы строк: [1] 11716 11669 11704 11624 11723
Суммы столбцов: [1]   313 57345   272   196   310


## Потерянные списки (1 балл)

В классе учатся `n` школьников. Известно, что некоторые из них участвовали в олимпиадах:
* `a` школьников участвовали в олимпиаде по математике
* `b` школьников - по информатике
* `c` школьников - по информатике

Однако, преподаватель потерял списки участников по каждому из предметов. Помогите учителю определить, сколько школьников могло не участвовать ни в какой олимпиаде. Выведите наибольшее и наименьшее возможное число таких.

Пример ввода:
```
10
7
5
3
```

Пример вывода:
```
0
3
```

In [4]:
# Функция для решения задачи
find_olympiad_participants <- function(n, a, b, c) {
  # n - всего школьников
  # a, b, c - участники по математике, информатике, информатике (вероятно опечатка в задании)
  # Предположим, что c - участники по физике (третья олимпиада)

  # Наибольшее число неучаствовавших:
  # Максимум, когда участники максимально пересекаются
  # min(n, a + b + c) - максимальное число участников хоть в одной олимпиаде
  max_participants <- min(n, a + b + c)
  max_not_participated <- n - max_participants

  # Наименьшее число неучаствовавших:
  # Когда участники минимально пересекаются (максимально разные люди)
  # Используем принцип включения-исключения
  # Для 3 множеств без данных о пересечениях используем верхнюю границу
  min_participants <- max(a, b, c, a + b - n, a + c - n, b + c - n, a + b + c - 2*n)
  min_participants <- max(0, min_participants)
  min_not_participated <- n - min_participants

  # Но для простоты в этой задаче (без данных о пересечениях):
  # Максимум неучаствовавших: когда участники не пересекаются, но может быть больше n
  # Минимум неучаствовавших: когда участники максимально пересекаются

  # Альтернативный подход (как в примере задачи):
  max_not_participated_simple <- max(0, n - (a + b + c))
  min_not_participated_simple <- max(0, n - min(n, a + b), n - min(n, a + c), n - min(n, b + c),
                                    n - min(n, max(a, b, c)))

  # Возвращаем результаты
  list(
    max_not_participated = max_not_participated,
    min_not_participated = min_not_participated,
    max_simple = max_not_participated_simple,
    min_simple = min_not_participated_simple
  )
}

# Пример из задания
n <- 10
a <- 7
b <- 5
c <- 3

result <- find_olympiad_participants(n, a, b, c)

print("Для примера из задания:")
cat(sprintf("Всего школьников: %d\n", n))
cat(sprintf("Участников по математике: %d\n", a))
cat(sprintf("Участников по информатике: %d\n", b))
cat(sprintf("Участников по третьему предмету: %d\n", c))
cat(sprintf("\nНаибольшее возможное число неучаствовавших: %d\n", result$max_simple))
cat(sprintf("Наименьшее возможное число неучаствовавших: %d\n", result$min_simple))

# Функция для ввода с консоли
solve_olympiad_problem <- function() {
  cat("Введите данные:\n")
  n <- as.integer(readline("Всего школьников (n): "))
  a <- as.integer(readline("Участников по математике (a): "))
  b <- as.integer(readline("Участников по информатике (b): "))
  c <- as.integer(readline("Участников по третьему предмету (c): "))

  # Простой расчет как в примере
  max_not <- max(0, n - (a + b + c))
  min_not <- max(0, n - min(n, a + b), n - min(n, a + c), n - min(n, b + c))

  cat("\nРезультат:\n")
  cat(sprintf("%d\n", max_not))
  cat(sprintf("%d\n", min_not))

  return(c(max_not, min_not))
}

# Для автоматической проверки (как в примере)
test_case <- function() {
  n <- 10
  a <- 7
  b <- 5
  c <- 3

  max_not <- max(0, n - (a + b + c))
  min_not <- max(0, n - min(n, a + b), n - min(n, a + c), n - min(n, b + c))

  cat("Тестовый случай (как в примере):\n")
  cat(sprintf("%d\n", max_not))
  cat(sprintf("%d\n", min_not))
}

# Выполняем тестовый случай
test_case()

[1] "Для примера из задания:"
Всего школьников: 10
Участников по математике: 7
Участников по информатике: 5
Участников по третьему предмету: 3

Наибольшее возможное число неучаствовавших: 0
Наименьшее возможное число неучаствовавших: 3
Тестовый случай (как в примере):
0
2


## Сложные узоры (2 балла)

Создайте матрицу 10×10 из случайных чисел.
Замените все элементы, стоящие ниже главной диагонали, на 0.
Затем замените все элементы выше диагонали на среднее значение по диагонали.

In [5]:
# Создаем матрицу 10×10 из случайных чисел
set.seed(123)
mat <- matrix(runif(100, min = 1, max = 100), nrow = 10, ncol = 10)

print("Исходная матрица 10x10:")
print(round(mat, 2))

# Сохраняем копию для сравнения
mat_original <- mat

# 1. Заменяем все элементы, стоящие ниже главной диагонали, на 0
for (i in 1:10) {
  for (j in 1:10) {
    if (i > j) {  # Ниже главной диагонали
      mat[i, j] <- 0
    }
  }
}

print("\nМатрица после замены элементов ниже главной диагонали на 0:")
print(round(mat, 2))

# 2. Вычисляем среднее значение по главной диагонали
diagonal_values <- diag(mat)
diag_mean <- mean(diagonal_values)

cat(sprintf("\nСреднее значение по главной диагонали: %.2f\n", diag_mean))
cat("Значения на диагонали: "); print(round(diagonal_values, 2))

# 3. Заменяем все элементы выше диагонали на среднее значение по диагонали
for (i in 1:10) {
  for (j in 1:10) {
    if (i < j) {  # Выше главной диагонали
      mat[i, j] <- diag_mean
    }
  }
}

print("\nМатрица после замены элементов выше диагонали на среднее:")
print(round(mat, 2))

# Визуализируем изменения
print("\nСравнение исходной и измененной матрицы:")

# Функция для красивого вывода
print_matrix_comparison <- function(original, modified, n = 5) {
  cat("Первые", n, "строк и столбцов:\n")
  cat("\nИсходная матрица:\n")
  print(round(original[1:n, 1:n], 2))

  cat("\nИзмененная матрица:\n")
  print(round(modified[1:n, 1:n], 2))

  # Подсчет измененных элементов
  changed_below <- sum(lower.tri(modified) & modified == 0)
  changed_above <- sum(upper.tri(modified) & modified == diag_mean)

  cat(sprintf("\nСтатистика изменений:\n"))
  cat(sprintf("Элементов ниже диагонали заменено на 0: %d\n", changed_below))
  cat(sprintf("Элементов выше диагонали заменено на %.2f: %d\n", diag_mean, changed_above))
}

print_matrix_comparison(mat_original, mat, 5)

# Альтернативный способ с использованием встроенных функций R
print("\nАльтернативное решение с использованием встроенных функций:")

# Создаем новую матрицу
mat2 <- matrix(runif(100, 1, 100), 10, 10)

# Заменяем элементы ниже диагонали на 0
mat2[lower.tri(mat2)] <- 0

# Вычисляем среднее по диагонали
diag_mean2 <- mean(diag(mat2))

# Заменяем элементы выше диагонали на среднее
mat2[upper.tri(mat2)] <- diag_mean2

print("Результат альтернативного решения (первые 5x5):")
print(round(mat2[1:5, 1:5], 2))

[1] "Исходная матрица 10x10:"
       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
 [1,] 29.47 95.73 89.06 96.34 15.14  5.54 66.85 75.69 25.12 13.94
 [2,] 79.04 45.88 69.59 90.33 42.04 44.78 10.39 63.29 67.14 65.66
 [3,] 41.49 68.08 64.41 69.38 41.96 80.09 39.01 71.31 42.35 35.01
 [4,] 88.42 57.69 99.43 79.75 37.52 13.07 28.16  1.06 79.03 66.02
 [5,] 94.11 11.19 65.91  3.44 16.09 56.53 81.65 48.06 11.18 32.72
 [6,]  5.51 90.08 71.14 48.30 14.74 21.45 45.40 22.79 44.05 19.58
 [7,] 53.28 25.36 54.86 76.09 24.07 13.63 81.20 38.60 98.51 78.45
 [8,] 89.35  5.16 59.82 22.42 47.13 75.58 81.43 61.66 89.41 10.27
 [9,] 55.59 33.46 29.63 32.50 27.33 89.61 79.64 35.83 88.76 47.21
[10,] 46.20 95.50 15.56 23.93 85.92 38.07 44.54 12.00 18.33 51.64
[1] "\nМатрица после замены элементов ниже главной диагонали на 0:"
       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
 [1,] 29.47 95.73 89.06 96.34 15.14  5.54 66.85 75.69 25.12 13.94
 [2,]  0.00 45.88 69.59 90.33 42.04 44.78 10

## Магическое число (2 балла)

Согласно определению предела последовательности
$$
A = \lim\limits_{n\to\infty} x_n :=
\forall\varepsilon > 0 ~~ \exists N \in\mathbb{N} : \forall n > N ~~ |x_n - A| < \varepsilon
$$

Петя решил найти этот номер `N` для некоторых $\varepsilon$. Для последовательности
$$
y_n = \frac{n+5}{n+2} \arccos{\sqrt{\frac{2+(-1)^n}{4}}}
$$

при $\varepsilon = 0.01$, $\varepsilon = 0.001$ найти такие номера `N`, начиная с которых становится верным неравенство $|x_n - A| < \varepsilon$.

Для тех, чей номер ИСУ заканчивается четной цифрой, использовать $A = \frac{\pi}{3}$ и последовательность $x_n = y_{2n}$

Для тех, чей номер ИСУ заканчивается нечетной цифрой, использовать $A = \frac{\pi}{6}$ и последовательность $x_n = y_{2n-1}$


При решениии можете использовать векторные вычисления или цикл `for`.


In [7]:
# Номер ИСУ: 311469 - заканчивается на 9 (нечетная цифра)
# Поэтому используем A = π/6 и последовательность x_n = y_{2n-1}

# Определяем функцию y_n
y_n <- function(n) {
  ((n + 5) / (n + 2)) * acos(sqrt((2 + (-1)^n) / 4))
}

# Определяем последовательность x_n = y_{2n-1}
x_n <- function(n) {
  y_n(2 * n - 1)
}

# Предел A = π/6
A <- pi / 6

print("Параметры задачи:")
cat(sprintf("Номер ИСУ заканчивается на 9 (нечетная цифра)\n"))
cat(sprintf("Используем A = π/6 ≈ %.6f\n", A))
cat(sprintf("Последовательность: x_n = y_{2n-1}\n"))

# Функция для нахождения N для заданного ε
find_N <- function(epsilon, max_iter = 10000) {
  for (n in 1:max_iter) {
    if (abs(x_n(n) - A) < epsilon) {
      return(n)
    }
  }
  return(NA)  # Если не нашли за max_iter итераций
}

# Находим N для ε = 0.01
epsilon1 <- 0.01
N1 <- find_N(epsilon1)

cat(sprintf("\nДля ε = %.3f:\n", epsilon1))
if (!is.na(N1)) {
  cat(sprintf("Найдено N = %d\n", N1))
  cat(sprintf("|x_%d - A| = %.6f\n", N1, abs(x_n(N1) - A)))
  cat(sprintf("x_%d = %.6f\n", N1, x_n(N1)))
} else {
  cat("Не удалось найти N за 10000 итераций\n")
}

# Находим N для ε = 0.001
epsilon2 <- 0.001
N2 <- find_N(epsilon2)

cat(sprintf("\nДля ε = %.4f:\n", epsilon2))
if (!is.na(N2)) {
  cat(sprintf("Найдено N = %d\n", N2))
  cat(sprintf("|x_%d - A| = %.8f\n", N2, abs(x_n(N2) - A)))
  cat(sprintf("x_%d = %.8f\n", N2, x_n(N2)))
} else {
  cat("Не удалось найти N за 10000 итераций\n")
}

# Векторный подход для проверки
print("\nПроверка векторным подходом:")

# Создаем вектор значений для проверки
n_values <- 1:20
x_values <- sapply(n_values, x_n)
differences <- abs(x_values - A)

print("Первые 20 значений последовательности:")
result_df <- data.frame(
  n = n_values,
  x_n = round(x_values, 6),
  |x_n - A| = round(differences, 6)
)
print(result_df)

# Находим, когда разность становится меньше epsilon
cat(sprintf("\nКогда |x_n - A| < %.3f? ", epsilon1))
first_small1 <- which(differences < epsilon1)[1]
if (!is.na(first_small1)) {
  cat(sprintf("Начиная с n = %d\n", first_small1))
} else {
  cat("Нет таких n в первых 20\n")
}

cat(sprintf("Когда |x_n - A| < %.4f? ", epsilon2))
first_small2 <- which(differences < epsilon2)[1]
if (!is.na(first_small2)) {
  cat(sprintf("Начиная с n = %d\n", first_small2))
} else {
  cat("Нет таких n в первых 20\n")
}

# Графическое представление
print("\nСоздаем график сходимости...")
# Увеличиваем диапазон для лучшей визуализации
n_range <- 1:50
x_range <- sapply(n_range, x_n)
diff_range <- abs(x_range - A)

# Устанавливаем графические параметры
old_par <- par(mfrow = c(2, 1))

# График 1: Значения последовательности
plot(n_range, x_range, type = "b", pch = 19, col = "blue",
     main = "Последовательность x_n и предел A",
     xlab = "n", ylab = "x_n",
     ylim = c(min(x_range), max(x_range)))
abline(h = A, col = "red", lty = 2, lwd = 2)
legend("topright", legend = c("x_n", "A = π/6"),
       col = c("blue", "red"), lty = c(1, 2), pch = c(19, NA))

# График 2: Разность с пределом
plot(n_range, diff_range, type = "b", pch = 19, col = "darkgreen",
     main = "|x_n - A|",
     xlab = "n", ylab = "|x_n - A|", log = "y")
abline(h = epsilon1, col = "orange", lty = 2, lwd = 2)
abline(h = epsilon2, col = "purple", lty = 2, lwd = 2)
legend("topright", legend = c("|x_n - A|", "ε = 0.01", "ε = 0.001"),
       col = c("darkgreen", "orange", "purple"), lty = c(1, 2, 2), pch = c(19, NA, NA))

# Восстанавливаем параметры
par(old_par)

ERROR: Error in parse(text = input): <text>:70:3: unexpected '|'
69:   x_n = round(x_values, 6),
70:   |
      ^


## Строим зиккурат! (2 балла)

Напишите функцию, которая принимает одно целое число `n`, и возвращает пронумерованные этажи зиккурата. Представим, что мы смотрим на зиккурат сверху вниз. Этажи зиккурата нумеруются с первого, ширина каждой ступеньки равна одной строке или столбцу.

Пример ввода:
```
4
```

Пример вывода:
```
1  1  1  1  1  1  1
1  2  2  2  2  2  1
1  2  3  3  3  2  1
1  2  3  4  3  2  1
1  2  3  3  3  2  1
1  2  2  2  2  2  1
1  1  1  1  1  1  1
```

In [8]:
# Функция для построения зиккурата
build_ziggurat <- function(n) {
  # Размер матрицы: 2n - 1
  size <- 2 * n - 1
  # Создаем пустую матрицу
  ziggurat <- matrix(0, nrow = size, ncol = size)

  # Заполняем матрицу
  for (i in 1:size) {
    for (j in 1:size) {
      # Определяем расстояние до ближайшего края
      # По горизонтали и вертикали
      dist_i <- min(i, size - i + 1)
      dist_j <- min(j, size - j + 1)

      # Значение - минимальное расстояние (но не больше n)
      ziggurat[i, j] <- min(dist_i, dist_j, n)
    }
  }

  return(ziggurat)
}

# Функция для красивого вывода зиккурата
print_ziggurat <- function(n) {
  ziggurat <- build_ziggurat(n)

  cat(sprintf("Зиккурат с %d этажами:\n", n))
  cat("Размер матрицы:", 2*n - 1, "x", 2*n - 1, "\n\n")

  # Выводим матрицу с выравниванием
  for (i in 1:nrow(ziggurat)) {
    for (j in 1:ncol(ziggurat)) {
      cat(sprintf("%2d ", ziggurat[i, j]))
    }
    cat("\n")
  }
}

# Тестируем функцию
print_ziggurat(4)

# Проверяем для разных n
test_ziggurats <- function() {
  for (n in 1:5) {
    cat(sprintf("\n=== Зиккурат для n = %d ===\n", n))
    print_ziggurat(n)
  }
}

# Запускаем тесты
test_ziggurats()

# Альтернативная реализация с использованием outer
build_ziggurat_vectorized <- function(n) {
  size <- 2 * n - 1
  indices <- 1:size

  # Создаем матрицы расстояний до центра
  row_dists <- pmin(indices, rev(indices))
  col_dists <- pmin(indices, rev(indices))

  # Используем outer для создания матрицы
  ziggurat <- outer(row_dists, col_dists, function(x, y) pmin(x, y))

  return(ziggurat)
}

# Сравниваем два подхода
cat("\n\nПроверка векторного подхода для n = 4:\n")
zig_vectorized <- build_ziggurat_vectorized(4)
print(zig_vectorized)

# Проверяем, что результаты совпадают
cat("\nРезультаты совпадают?",
    all(build_ziggurat(4) == build_ziggurat_vectorized(4)), "\n")

# Функция для пользовательского ввода
interactive_ziggurat <- function() {
  cat("Введите число этажей зиккурата (n): ")
  n <- as.integer(readline())

  if (is.na(n) || n < 1) {
    cat("Некорректный ввод. Используется n = 3\n")
    n <- 3
  }

  print_ziggurat(n)
}

# Запускаем интерактивный режим
# interactive_ziggurat()

Зиккурат с 4 этажами:
Размер матрицы: 7 x 7 

 1  1  1  1  1  1  1 
 1  2  2  2  2  2  1 
 1  2  3  3  3  2  1 
 1  2  3  4  3  2  1 
 1  2  3  3  3  2  1 
 1  2  2  2  2  2  1 
 1  1  1  1  1  1  1 

=== Зиккурат для n = 1 ===
Зиккурат с 1 этажами:
Размер матрицы: 1 x 1 

 1 

=== Зиккурат для n = 2 ===
Зиккурат с 2 этажами:
Размер матрицы: 3 x 3 

 1  1  1 
 1  2  1 
 1  1  1 

=== Зиккурат для n = 3 ===
Зиккурат с 3 этажами:
Размер матрицы: 5 x 5 

 1  1  1  1  1 
 1  2  2  2  1 
 1  2  3  2  1 
 1  2  2  2  1 
 1  1  1  1  1 

=== Зиккурат для n = 4 ===
Зиккурат с 4 этажами:
Размер матрицы: 7 x 7 

 1  1  1  1  1  1  1 
 1  2  2  2  2  2  1 
 1  2  3  3  3  2  1 
 1  2  3  4  3  2  1 
 1  2  3  3  3  2  1 
 1  2  2  2  2  2  1 
 1  1  1  1  1  1  1 

=== Зиккурат для n = 5 ===
Зиккурат с 5 этажами:
Размер матрицы: 9 x 9 

 1  1  1  1  1  1  1  1  1 
 1  2  2  2  2  2  2  2  1 
 1  2  3  3  3  3  3  2  1 
 1  2  3  4  4  4  3  2  1 
 1  2  3  4  5  4  3  2  1 
 1  2  3  4  4  4  3  

## Пишем Counter на R (2 балла)

В питоне есть структура `Counter`, которая на заданном наборе данных создает словарь, в котором по каждому элементу хранит информацию о том сколько данное числов встретилось в наборе.

Вам необходимо реализовать похожу функцию, но без создания структуры. Пусть дан целочисленный вектор `x`. Вам необходимо вывести информацию о том, какой элемент сколько раз встретился в этом векторе. Элементы должны быть упорядочены по возрастанию.

Так, для вектора
```R
x <- c(5, 2, 7, 7, 7, 2, 0, 0)
```

вам нужно вывести

Пример вывода:
```
0 2 5 7
2 2 1 3
```

In [9]:
# Реализация Counter на R
my_counter <- function(x) {
  # Проверяем входные данные
  if (!is.numeric(x)) {
    stop("Входной вектор должен быть числовым")
  }

  # Преобразуем в целые числа, если нужно
  x <- as.integer(x)

  # Получаем уникальные элементы и сортируем их
  unique_elements <- sort(unique(x))

  # Подсчитываем частоту каждого элемента
  counts <- sapply(unique_elements, function(elem) sum(x == elem))

  # Возвращаем результат в виде списка
  result <- list(
    elements = unique_elements,
    counts = counts
  )

  return(result)
}

# Функция для вывода в формате как в задании
print_counter <- function(x) {
  counter <- my_counter(x)

  # Выводим элементы
  cat(paste(counter$elements, collapse = " "), "\n")

  # Выводим счетчики
  cat(paste(counter$counts, collapse = " "), "\n")
}

# Тестируем на примере из задания
x <- c(5, 2, 7, 7, 7, 2, 0, 0)

cat("Входной вектор:\n")
print(x)

cat("\nРезультат Counter:\n")
print_counter(x)

# Дополнительные тесты
test_counter <- function() {
  cat("\n=== Дополнительные тесты ===\n")

  # Тест 1: Все элементы разные
  x1 <- c(1, 2, 3, 4, 5)
  cat("\nТест 1 (все элементы разные):\n")
  cat("Вектор: "); print(x1)
  cat("Результат:\n"); print_counter(x1)

  # Тест 2: Все элементы одинаковые
  x2 <- c(3, 3, 3, 3, 3)
  cat("\nТест 2 (все элементы одинаковые):\n")
  cat("Вектор: "); print(x2)
  cat("Результат:\n"); print_counter(x2)

  # Тест 3: Пустой вектор
  x3 <- integer(0)
  cat("\nТест 3 (пустой вектор):\n")
  cat("Вектор: "); print(x3)
  cat("Результат:\n");
  tryCatch(print_counter(x3), error = function(e) cat("Ошибка:", e$message, "\n"))

  # Тест 4: Большой вектор
  set.seed(42)
  x4 <- sample(1:5, 20, replace = TRUE)
  cat("\nТест 4 (случайный вектор):\n")
  cat("Вектор: "); print(x4)
  cat("Результат:\n"); print_counter(x4)
}

# Запускаем тесты
test_counter()

# Альтернативная реализация с использованием table()
counter_with_table <- function(x) {
  # Используем встроенную функцию table
  tbl <- table(x)

  # Преобразуем в нужный формат
  elements <- as.integer(names(tbl))
  counts <- as.vector(tbl)

  # Сортируем по элементам
  order_idx <- order(elements)
  elements <- elements[order_idx]
  counts <- counts[order_idx]

  return(list(elements = elements, counts = counts))
}

# Сравниваем две реализации
cat("\n=== Сравнение с использованием table() ===\n")
x_test <- c(5, 2, 7, 7, 7, 2, 0, 0)

counter1 <- my_counter(x_test)
counter2 <- counter_with_table(x_test)

cat("Реализация my_counter:\n")
print_counter(x_test)

cat("\nРеализация с table():\n")
cat(paste(counter2$elements, collapse = " "), "\n")
cat(paste(counter2$counts, collapse = " "), "\n")

cat("\nРезультаты совпадают?",
    all(counter1$elements == counter2$elements) &&
    all(counter1$counts == counter2$counts), "\n")

# Функция для интерактивного тестирования
interactive_counter <- function() {
  cat("Введите числа через пробел: ")
  input <- readline()

  # Преобразуем строку в числовой вектор
  x <- as.numeric(unlist(strsplit(input, " ")))

  # Убираем NA значения
  x <- x[!is.na(x)]

  if (length(x) == 0) {
    cat("Некорректный ввод\n")
    return()
  }

  cat("\nВходной вектор:\n")
  print(x)

  cat("\nРезультат Counter:\n")
  print_counter(x)
}

# Запускаем интерактивный режим
# interactive_counter()

Входной вектор:
[1] 5 2 7 7 7 2 0 0

Результат Counter:
0 2 5 7 
2 2 1 3 

=== Дополнительные тесты ===

Тест 1 (все элементы разные):
Вектор: [1] 1 2 3 4 5
Результат:
1 2 3 4 5 
1 1 1 1 1 

Тест 2 (все элементы одинаковые):
Вектор: [1] 3 3 3 3 3
Результат:
3 
5 

Тест 3 (пустой вектор):
Вектор: integer(0)
Результат:
 
 

Тест 4 (случайный вектор):
Вектор:  [1] 1 5 1 1 2 4 2 2 1 4 1 5 4 2 2 3 1 1 3 4
Результат:
1 2 3 4 5 
7 5 2 4 2 

=== Сравнение с использованием table() ===
Реализация my_counter:
0 2 5 7 
2 2 1 3 

Реализация с table():
0 2 5 7 
2 2 1 3 

Результаты совпадают? TRUE 
